### ISSUE TITLE
The documentation does not tell you how to use lipsum

### ISSUE THREAD

**Issue by ghost** [paulhorner79/atom-lipsum#4]
I'm about to say forget it!  The main page here only describes what they options are but nothing about how to use them.  it's the sort of task that shouldn't take more than a few seconds to accomplish. Why doesn't someone give some instruction on what keys to press and what characters to type into your text editor that will result in some lipsum being generated? Two sentences even

**Comment by paulhorner79** [comment]
There are two sentences in the readme - https://github.com/paulhorner79/atom-lipsum#how-to-use

Right click, choose "Lipsum" and then decide whether you want to add a sentence or a paragraph.  If you want to use the keyboard, you can use the command palette (`ctrl+shift+p`) then type `lipsum` and choose the options using the arrow keys. As far as I know there are no other keyboard shortcuts but you can define some locally if you want.

I stopped using Atom some time ago because it was using too much memory and killing my machine.  As such I don't know if this is still working or not (and that's why I haven't  looked at the other issues/pull requests).  I haven't touched it in a couple of years so there might be a better Lipsum plugin available now.

**Comment by ghost** [comment]
Thank you
 

Sent: Friday, February 23, 2018 at 5:46 AM
